# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='产品标题')),
                ('pric', models.ImageField(default=0, upload_to='', verbose_name='促销价')),
            ],
        ),
    ]
