# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 06:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('is_main', models.BooleanField(default=False, verbose_name='主图')),
                ('order', models.IntegerField(default=0, help_text='数字越小,位址越前', verbose_name='序号')),
                ('img', models.ImageField(upload_to='', verbose_name='图片地址')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='pric',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='商品详情'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=100, help_text='填写1～100,100表示原价', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='折扣比例'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, '男士'), (2, '女士'), (3, '情侣')], db_index=True, default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='product',
            name='num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='吊牌价'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_out',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销售价'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, '上装'), (2, '下装'), (3, '鞋履'), (4, '配饰')], db_index=True, default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='productpic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pic', to='store.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Category', verbose_name='所属分类'),
        ),
    ]
