# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181128_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_out',
            new_name='sales_count',
        ),
    ]
